-- ============================================================
-- PENDING MIGRATIONS
--
-- This file used to inline the SQL to paste into the Supabase SQL Editor. It
-- now points at the files instead, because the privacy-minimisation release has
-- an ORDER and a review step in the middle of it, and a single paste-everything
-- block would invite skipping the review.
--
-- Apply in this order:
--
--   1. migrations/0009_upload_stats.sql
--      Creates public.upload_stats (user_id, total_upload_count, updated_at),
--      its RLS policy and the atomic increment/read RPCs, and backfills the
--      totals from public.upload_events. Reads the old table; changes nothing
--      in it. Also drops the retired get_upload_stats(text) RPC.
--
--   2. migrations/0010_lock_legacy_writes.sql
--      Makes public.designs, public.spreadsheet_batches, public.sales_reports
--      and public.upload_events read-only, and revokes the browser's write
--      access to the `designs` Storage bucket. Deletes nothing. Step 6 of that
--      file documents how to make the public bucket inaccessible; it is
--      deliberately not executed.
--
--   3. INSPECT_LEGACY_DATA.sql            <-- READ-ONLY. Run it and READ IT.
--      Reports what artwork and listing content is currently stored, and
--      reconciles the old per-upload events against the new counter. Section D
--      must show delta = 0 for every user before any cleanup is considered.
--
--   4. migrations/0011_cleanup_legacy_data.sql
--      *** INERT AS SHIPPED. *** Every destructive statement in it is commented
--      out. Do not uncomment anything until the inspection above has been
--      reviewed and the owner has approved deleting that specific data.
--
-- 0007_upload_events.sql and 0008_sales_reports.sql are still in the migrations
-- directory because migrations are forward-only and must not be rewritten after
-- they are applied. The tables they created are superseded; 0010 freezes them
-- and 0011 is where they are removed, once approved.
-- ============================================================
